/*
 * LB Loan Management API
 * API for loan management
 *
 * OpenAPI spec version: 0.0.1
 * Contact: raynard.eiger@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package loans.model;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Rate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-10-17T20:30:36.362Z[GMT]")
@Entity
public class Rate {
	
	@JsonProperty("id")
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private UUID id = null;

	@JsonProperty("type")
	private String type = null;

	// Ideally, this should be BigDecimal
	@JsonProperty("rate")
	private Double rate = null;

	@JsonProperty("startDate")
	@JsonFormat(pattern = "dd-MM-yyyy")
	private LocalDate startDate = null;
	
	public Rate id(UUID id) {
		this.id = id;
		return this;
	}

	@Schema(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", required = true, description = "")
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public Rate type(String type) {
		this.type = type;
		return this;
	}

	/**
	 * Get type
	 * 
	 * @return type
	 **/
	@Schema(example = "fixed", required = true, description = "")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Rate rate(Double rate) {
		this.rate = rate;
		return this;
	}

	@Schema(example = "3.75", required = true, description = "")
	public Double getRate() {
		return rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Rate startDate(LocalDate startDate) {
		this.startDate = startDate;
		return this;
	}

	@Schema(required = true, description = "")
	public LocalDate getStartDate() {
		return startDate;
	}

	public void setStartDate(LocalDate startDate) {
		this.startDate = startDate;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Rate rate = (Rate) o;
		return Objects.equals(this.type, rate.type) && Objects.equals(this.rate, rate.rate)
		    && Objects.equals(this.startDate, rate.startDate);
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(type, rate, startDate);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Rate {\n");

		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
		sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
